<?php
if (null != $this->headlineRow) {

    //Title
    $this->headTitle(Magazine_Model_Magazine::getDefaultMagazine()->title, 'PREPEND');
    if (isset($this->headlineRow->article->categories[0])) :
        $this->headTitle($this->headlineRow->categories[0]->name, 'PREPEND');
    endif;
    $this->headTitle($this->headlineRow->article->title, 'PREPEND')
        ->headTitle($this->translate('Actualités'), 'PREPEND')
        ->setSeparator(' - ');

    //Meta description
    $this->headMeta()->setName('description', $this->translate('Dossier, portraits, interviews : découvrez les vins du Rhône à travers ceux qui les font vivre.'));

    //Meta keywords
    $this->headMeta()->setName('keywords', $this->translate('Vins, AOC, Côtes du Rhône, Vallée du Rhône, Actualités, Magazine, Actualités'));
}
?>

<?php
    $this->placeholder('body_id')->set('tmp-magazinemonth');

    $this->articleRight = array();
    $this->articleLeft = array();
    foreach ($this->childRowset as $key => $data) {
        if ($key == 0 || $key % 2 == 0) {
            $this->articleLeft[$key] = $data->article;
        } else {
            $this->articleRight[$key] = $data->article;
        }
    }
?>

<?php
    // Navigation du magazine courant
    $navigation = $this->getMagazineNavigation($this->magazineRow);
    echo $this->partial('magazine/_navigation.phtml', array(
        'magazineRow' => $this->magazineRow,
        'navigation' => $navigation,
        'url' => $this->headlineRow->permalink,
    ));
?>

<section class="monthbg row">
    <div class="row box-month">
        <div class="cell-12">
            <h3><?php echo $this->translate('Dossier du Mois') ?></h3>
            <figure>
                <a href="<?php echo $this->childRowset[0]->permalink ?>"><img src="<?php echo $this->headlineRow->article->getCoverOrPx()->getStaticUrl(array('cropcenterresize' => array('width' => 900, 'height' => 380))) ?>" class="picture"></a>
                <figcaption>
                    <h2 class="heading-6"><?php echo $this->headlineRow->article->title ?></h2>
                    <a href="<?php echo $this->childRowset[0]->permalink ?>"><span class="icon icon-pager-next"></span></a>
                </figcaption>
            </figure>
            <p class="teasing-2"><a href="<?php echo $this->childRowset[0]->permalink ?>"><?php echo $this->headlineRow->article->subtitle ?></a></p>
        </div>
    </div>
    <div class="row sidebar-large sidebar-large-cell-4">
        <div class="cell-8">
            <div class="entry">
                <ol class="box-media-list">
                    <?php foreach ($this->articleLeft as $key => $articleRow) : ?>
                    <?php if (0 == $key) : ?>
                    <li>
                        <div class="box-media">
                            <div class="block">
                                <a href="<?php echo $this->childRowset[$key]->permalink  ?>">
                                    <h3 class="heading-3"><?php echo $articleRow->title ?></h3>
                                </a>
                                <span class="detail"><a href="<?php echo $this->childRowset[$key]->permalink ?>"><?php echo $articleRow->author->fullname; ?></a> | 15/12/11</span>
                                <a href="<?php echo $this->childRowset[$key]->permalink  ?>">
                                    <img src="<?php echo $articleRow->getCoverOrPx()->getStaticUrl(array('cropcenterresize' => array('width' => 570, 'height' => 240))) ?>" alt="" width="570" height="240" class="picture">
                                </a>                                <p><?php echo $this->getAbstract($articleRow) ?> <span class="dotdotdot">•••</span> </p>
                                <a class="more" href="<?php echo $this->childRowset[$key]->permalink ?>"><?php echo $this->translate('Lire la suite') ?> <img src="/layouts/frontoffice/images/px.png" width="16" height="16" class="icon icon-more"></a>
                            </div>
                        </div>
                    </li>
                    <?php else : ?>
                    <li>
                        <div class="box-media">
                            <a href="<?php echo $this->childRowset[$key]->permalink  ?>" class="media">
                                <img src="<?php echo $articleRow->getCoverOrPx()->getStaticUrl(array('cropcenterresize' => array('width' => 160, 'height' => 110))) ?>" width="160" height="110" class="picture">
                            </a>
                            <div class="block">
                                <a href="<?php echo $this->childRowset[$key]->permalink  ?>">
                                    <h3 class="heading-3"><?php echo $articleRow->title ?></h3>
                                </a>
                                <span class="detail"><a href="<?php echo $articleRow->author->permalink ?>"><?php echo $articleRow->author->fullname ?></a> | 15/12/11</span>
                                <p><?php echo $this->getAbstract($articleRow) ?> <span class="dotdotdot">•••</span> </p>
                                <a class="more" href="<?php echo $this->childRowset[$key]->permalink ?>"><?php echo $this->translate('Lire la suite') ?> <img src="/layouts/frontoffice/images/px.png" width="16" height="16" class="icon icon-more"></a>
                            </div>
                        </div>
                    </li>
                    <?php endif; ?>
                    <?php endforeach; ?>
                </ol>
            </div>
        </div>
        <div class="cell-4 cell-last">
            <aside class="sidebar">
                <ol class="box-media-list">
                    <?php foreach ($this->articleRight as $key => $articleRow) : ?>
                    <li>
                        <div class="box-media">
                            <div class="block">

                                <a href="<?php echo $this->childRowset[$key]->permalink ?>">
                                    <h3 class="heading-3"><?php echo $articleRow->title ?></h3>
                                </a>
                                <span class="detail"><a href="<?php echo $articleRow->author->permalink ?>"><?php echo $articleRow->author->fullname ?></a> | 15/12/11</span>
                                <a href="<?php echo $this->childRowset[$key]->permalink ?>">
                                    <img src="<?php echo $articleRow->getCoverOrPx()->getStaticUrl(array('cropcenterresize' => array('width' => 280, 'height' => 150))) ?>" alt="" width="280" height="150" class="picture">
                                </a>
                                <p><?php echo $this->getAbstract($articleRow) ?> <span class="dotdotdot">•••</span> </p>
                                <a class="more" href="<?php echo $this->childRowset[$key]->permalink ?>"><?php echo $this->translate('Lire la suite') ?> <img src="/layouts/frontoffice/images/px.png" width="16" height="16" class="icon icon-more"></a>
                            </div>
                        </div>
                    </li>
                    <?php endforeach; ?>
                </ol>
            </aside>
        </div>
    </div>
</section>
