<?php
if (null != $this->magazineArticleRow) {
    //Title
    $this->headTitle($this->magazineArticleRow->magazine->title, 'PREPEND');
    if (isset($this->magazineArticleRow->article->categories[0])) :
        $this->headTitle($this->magazineArticleRow->article->categories[0]->name, 'PREPEND');
    endif;
    $this->headTitle($this->magazineArticleRow->article->title, 'PREPEND')
        ->headTitle($this->translate('Interview'), 'PREPEND')
        ->setSeparator(' - ');

    //Meta description
    $this->headMeta()->setName('description', $this->translate('Dossier, portraits, interviews : découvrez les vins du Rhône à travers ceux qui les font vivre.'));

    //Meta keywords
    $this->headMeta()->setName('keywords', $this->translate('Vins, AOC, Côtes du Rhône, Vallée du Rhône, Actualités, Magazine, Interview'));
}
?>
<?php
    $this->placeholder('body_id')->set('tmp-magazineitw');
?>

<?php
    // Dossier > Categorie
    if (null !== $this->magazineArticleRow->child) {
        $url = $this->magazineArticleRow->parent->parent->permalink;
    } elseif (isset($this->magazineArticleRow->article->categories[0])
        && null !== $this->magazineArticleRow->article->categories[0]) {
        $url = $this->magazineArticleRow->article->categories[0]->permalink;
    } else {
        $url = null;
    }

    // Navigation du magazine courant
    $navigation = $this->getMagazineNavigation($this->magazineRow);
    echo $this->partial('magazine/_navigation.phtml', array(
        'magazineRow' => $this->magazineRow,
        'navigation' => $navigation,
        'url' => $url,
    ));
?>
<section class="monthbg row">
    <header class="row">
        <div class="cell-5">
            <div class="profile-picture">
                <img src="<?php echo $this->magazineArticleRow->article->getPictureOrPx()->getStaticUrl(array('cropcenterresize' => array('width' => '300', 'height' => '352'))) ?>" class="picture" width="300" height="352" />
            </div>
        </div>
        <div class="cell-7 cell-last">
            <hgroup>
                <h1 class="heading-5"><?php echo $this->magazineArticleRow->article->citation ?></h1>
                <h3 class="heading-6"><?php echo $this->magazineArticleRow->article->subtitle ?></h3>
                <?php $date = $this->magazineArticleRow->article->getDateObjectByPublished_at(); ?>
                <span class="detail">
                    <?php echo $this->translate('%s par %s', $date->get(Zend_Date::DATE_FULL), $this->magazineArticleRow->article->author->fullname) ?>
                </span>
                <hr class="tiny">
            </hgroup>
            <h5 class="heading-7"><?php echo $this->magazineArticleRow->article->title ?></h5>
        </div>
    </header>
    <hr class="dotted">
    <div class="row sidebar-large sidebar-large-cell-3">
        <div class="cell-9">
            <div class="entry">
                <p class="teasing-2"><?php echo $this->magazineArticleRow->article->abstract ?></p>

                <div class="list-itw">
                    <?php echo $this->magazineArticleRow->article->body ?>
                </div>
                <?php /*Retrouvez Claudine Vigier sur son site : <a href="#" class="url">http://claudine.com <img src="/layouts/frontoffice/images/px.png"  width="16" height="16" class="icon icon-url"/></a> */ ?>

                <aside>
                    <?php if (count($this->tagRowset) != 0) :?>
                    <div class="tags">
                        <h4 class="heading-3"><?php echo $this->translate('Tags') ?></h4>
                        <ul class="tag-list">
                            <?php foreach ($this->tagRowset as $tagRow) : ?>
                            <li><a href="<?php echo $this->url(array('slug' => $tagRow->slug), 'magazine_article_tag') ?>"><?php echo $tagRow->name ?></a></li>
                            <?php endforeach ; ?>
                        </ul>
                    </div>
                    <?php endif;?>


                    <!--<div class="related">
                        <div>
                            <?php if (null !== $this->previousMagazineArticleRow) : ?>
                            <a href="<?php echo $this->previousMagazineArticleRow->permalink ?>"><span class="icon icon-next-big"></span><?php echo $this->previousMagazineArticleRow->article->title; ?></a>
                            <?php endif; ?>
                        </div>
                        <div>
                            <?php if (null !== $this->nextMagazineArticleRow) : ?>
                            <a href="<?php echo $this->nextMagazineArticleRow->permalink ?>"><span class="icon icon-prev-big"></span><?php echo $this->nextMagazineArticleRow->article->title; ?></a>
                            <?php endif; ?>
                        </div>
                    </div>--> <!-- /.related -->

                </aside>
            </div>
        </div>
        <div class="cell-3 cell-last">
            <aside class="sidebar">
                <?php
                if (isset($this->isChild) && true === $this->isChild) {
                    echo $this->partial('magazine-article/bloc/_headlineArticleList.phtml', array('headlineRow' => $this->headlineRow, 'childRowset' => $this->childRowset, 'articleRow' => $this->articleRow, 'magazineRow' => $this->magazineRow));
                }
                ?>

                <?php if (null != $this->relatedArticleRowset) : ?>
                <h3 class="heading-6"><?php echo $this->translate('Sur le même sujet') ?></h3>
                <ul class="news-list">
                    <?php if (null != $this->relatedArticleRowset) : ?>
                    <?php foreach ($this->relatedArticleRowset as $relatedArticleRow) : ?>
                        <li>
                            <a href="<?php echo $relatedArticleRow->permalink; ?>">
                                <img src="<?php echo $relatedArticleRow->article->getCoverOrPx()->getStaticUrl(array('cropcenterresize' => array('width' => '60', 'height' => '60'))); ?>" height="60" width="60" class="picture media-illus" />
                                <div class="media-inner">
                                    <strong><?php echo $relatedArticleRow->article->title; ?></strong>
                                    <small><?php echo $relatedArticleRow->article->getDateObjectBy('published_at')->get('dd.MM.YYY'); ?></small>
                                </div>
                            </a>
                        </li>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </ul>
                <?php endif ?>

                <?php if (null != $this->lastArticleRowset) : ?>
                <h3 class="heading-6"><?php echo $this->translate('Dernières actualités') ?></h3>
                <ul class="news-list">
                    <?php foreach ($this->lastArticleRowset as $lastArticleRow) : ?>
                    <li>
                        <a href="<?php echo $lastArticleRow->permalink; ?>">
                            <img src="<?php echo $lastArticleRow->article->getCoverOrPx()->getStaticUrl(array('cropcenterresize' => array('width' => '60', 'height' => '60'))); ?>" height="60" width="60" class="picture media-illus" />
                            <div class="media-inner">
                                <strong><?php echo $lastArticleRow->article->title; ?></strong>
                                <small><?php echo $lastArticleRow->article->getDateObjectBy('published_at')->get('dd.MM.YYY'); ?></small>
                            </div>
                        </a>
                    </li>
                    <?php endforeach; ?>
                </ul>

                <hr />
                <?php endif; ?>
            </aside>
        </div>
    </div>
</section>