<?php
if (null != $this->articleRow) {
    //Title
    $this->headTitle(Magazine_Model_Magazine::getDefaultMagazine()->title, 'PREPEND');
    if (isset($this->articleRow->categories[0])) :
        $this->headTitle($this->articleRow->categories[0]->name, 'PREPEND');
    endif;
    $this->headTitle($this->articleRow->title, 'PREPEND')
        ->headTitle($this->translate('Actualités'), 'PREPEND')
        ->setSeparator(' - ');

    //Meta description
    $this->headMeta()->setName('description', $this->translate('Dossier, portraits, interviews : découvrez les vins du Rhône à travers ceux qui les font vivre.'));

    //Meta keywords
    $this->headMeta()->setName('keywords', $this->translate('Vins, AOC, Côtes du Rhône, Vallée du Rhône, Actualités, Magazine, Actualités'));
}
?>

<?php
if (!empty($this->articleRow->video_link)) {
    $this->InlineScript()->prependFile('/layouts/frontoffice/js/plugins/jwplayer/jwplayer.js');
}
?>
<?php
$this->placeholder('body_id')->set('tmp-magazine');

//Initializing the object for the view helper "share with friends"
if (null != $this->articleRow) {
    $object = new stdClass();
    $object->title = $this->articleRow->title;
    $object->description = $this->smartTextCrop()->simpleTextCrop($this->getAbstract($this->articleRow), 100);
    $object->image = null;
    $object->url = $this->serverUrl($this->magazineArticleRow->permalink);
    if (!empty($this->articleRow->cover_id)) {
        $object->image = $this->serverUrl($this->articleRow->cover->getStaticUrl(
            array(
                'resize' => array(
                    'width' => 100,
                    'height'=> 100
                ))));
    }
}
?>

<?php
    // Dossier > Categorie
    if (null !== $this->magazineArticleRow->child) {
        $url = $this->magazineArticleRow->parent->parent->permalink;
    } elseif (isset($this->magazineArticleRow->article->categories[0])
              && null !== $this->magazineArticleRow->article->categories[0]) {
        $url = $this->magazineArticleRow->article->categories[0]->permalink;
    } else {
        $url = null;
    }

    // Navigation du magazine courant
    $navigation = $this->getMagazineNavigation($this->magazineRow);
    echo $this->partial('magazine/_navigation.phtml', array(
        'magazineRow' => $this->magazineRow,
        'navigation' => $navigation,
        'url' => $url,
    ));
?>

<div class="row">
    <div class="cell-12">
        <header class="article-header">
            <h1 class="heading-2"><?php echo $this->articleRow->title ?></h1>
            <aside>
                <img src="<?php echo $this->articleRow->author->getPictureOrPx()->getStaticUrl(array('cropcenterresize' => array('width' => 28, 'height' => 28))) ?>" class="picture float-left" width="28" height="28" />
                <?php
                    $date = $this->articleRow->getDateObjectByPublished_at();
                    echo $this->translate('%s par %s', $date->get(Zend_Date::DATE_FULL), $this->articleRow->author->fullname)
                ?>
            </aside>
        </header>
    </div>
</div>
<div class="row">
<div class="cell-9">
    <article class="article">
        <figure>
            <?php if (!empty($this->articleRow->video_link)) : ?>
            <div class="outer-video-player">
                <div id="video" class="video-js"></div>
                <?php $this->InlineScript()->captureStart(); ?>
                jwplayer("video").setup({
                    flashplayer: "/layouts/frontoffice/js/plugins/jwplayer/player.swf",
                    file: "<?php echo $this->articleRow->video_link ?>",
                    //flashvars="file=<?php echo $this->articleRow->video_link ?>",
                    height: 336,
                    width: 664
                });
                <?php $this->InlineScript()->captureEnd(); ?>
            </div>
            <?php else : ?>
            <img src="<?php echo $this->articleRow->getPictureOrPx()->getStaticUrl(array('cropcenterresize' => array('width' => 672, 'height' => 336))) ?>" class="picture" height="336" width="672" />
            <?php endif; ?>
            <figcaption><?php echo $this->articleRow->subtitle ?></figcaption>
        </figure>
        <div class="row">
            <div class="cell-8 prepend-1 entry">

                <?php
                $dataShareMail = $this->ShareWithFriends(Ir_Model_ShareWithFriends::TYPE_EMAIL, Ir_Model_ShareWithFriends::MODE_ADVANCED, $object);
                $dataShareFacebook = $this->ShareWithFriends(Ir_Model_ShareWithFriends::TYPE_FACEBOOK, Ir_Model_ShareWithFriends::MODE_ADVANCED, $object);
                //Filling the meta for the facebook share
                if (null != $dataShareFacebook) :
                    $this->placeholder('meta_facebook')->set($dataShareFacebook['content']);
                endif;
                $dataShareTwitter = $this->ShareWithFriends(Ir_Model_ShareWithFriends::TYPE_TWITTER, Ir_Model_ShareWithFriends::MODE_ADVANCED, $object);
                ?>
                <div class="share">
                    <ul>
                        <li><a href="<?php echo $dataShareMail['url'] ?>"><span class="icon icon-share-google"></span></a></li>
                        <li><a href="<?php echo $dataShareFacebook['url'] ?>"><span class="icon icon-share-facebook"></span></a></li>
                        <li><a href="<?php echo $dataShareTwitter['url'] ?>"><span class="icon icon-share-twitter"></span></a></li>
                    </ul>
                </div>

                <hr/>

                <?php echo $this->articleRow->body ?>

            </div> <!-- /.entry -->
        </div> <!-- /.row -->
        <aside>
            <?php if (count($this->tagRowset) != 0) :?>
            <div class="tags">
                <h4 class="heading-3"><?php echo $this->translate('Tags') ?></h4>
                <ul class="tag-list">
                    <?php foreach ($this->tagRowset as $tagRow) : ?>
                    <li><a href="<?php echo $this->url(array('slug' => $tagRow->slug), 'magazine_article_tag') ?>"><?php echo $tagRow->name ?></a></li>
                    <?php endforeach ; ?>
                </ul>
            </div>  <!-- /.tag -->
            <?php endif;?>

            <div class="author">
                <div class="author-illus float-left">
                        <img src="<?php echo $this->articleRow->author->getPictureOrPx()->getStaticUrl(array('cropcenterresize' => array('width' => 80, 'height' => 80))) ?>" alt="<?php echo $this->articleRow->author->fullname ?>" width="80" height="80" sclass="picture" />
                </div>
                <div class="author-text">
                    <h5 class="heading-3"><?php echo $this->articleRow->author->fullname ?></h5>
                    <?php if (null !== $this->articleRow->author->getPrimaryGroup()) : ?>
                        <small><span>&#9733;</span> <?php echo $this->articleRow->author->getPrimaryGroup()->name ?></small>
                    <?php endif; ?>
                    <p><?php echo  $this->articleRow->author->abstract ?></p>
                    <?php if (null !== $this->articleRow->author->url_blog) : ?>
                    <a href="<?php echo $this->articleRow->author->url_blog ?>" class="more"><?php echo $this->translate('Le blog de %s', $this->articleRow->author->firstname) ?> <img src="/layouts/frontoffice/images/px.png" class="icon icon-more" height="16" width="16" /></a>
                    <?php endif; ?>
                </div>
            </div> <!-- /.author -->

            <!--------------------------------------------------------------------------------------------------------->
            <?php /**/?>
            <div class="related">
                <div>
                    <?php if (null !== $this->previousMagazineArticleRow) : ?>
                        <a href="<?php echo $this->previousMagazineArticleRow->permalink ?>">
                            <span class="icon icon-prev-big"></span><?php echo $this->previousMagazineArticleRow->article->title; ?>
                        </a>
                    <?php endif; ?>
                </div>
                <div>
                    <?php if (null !== $this->nextMagazineArticleRow) : ?>
                        <a href="<?php echo $this->nextMagazineArticleRow->permalink ?>">
                            <span class="icon icon-next-big"></span><?php echo $this->nextMagazineArticleRow->article->title; ?>
                        </a>
                    <?php endif; ?>
                </div>
            </div> <!-- /.related -->
            <?php /**/ ?>
            <!--------------------------------------------------------------------------------------------------------->

<!--            <div class="related">-->
<!--                <div>-->
<!--                    --><?php //if (null !== $this->magazineArticleNextRow) : ?>
<!--                    <a href="--><?php //echo $this->magazineArticleNextRow->permalink ?><!--"><span class="icon icon-next-big"></span>--><?php //echo $this->magazineArticleNextRow->article->title; ?><!--</a>-->
<!--                    --><?php //endif; ?>
<!--                </div>  -->
<!--                <div>-->
<!--                    --><?php //if (null !== $this->magazineArticlePrevRow) : ?>
<!--                    <a href="--><?php //echo $this->magazineArticlePrevRow->permalink ?><!--"><span class="icon icon-prev-big"></span>--><?php //echo $this->magazineArticlePrevRow->article->title; ?><!--</a>-->
<!--                    --><?php //endif; ?>
<!--                </div>-->
<!--            </div> <!-- /.related -->
        </aside>
    </article>
</div>
<div class="cell-3 cell-last">
    <section class="sidebar">

        <?php 
            if (isset($this->isChild) && true === $this->isChild) {
                //@TODO : Dynamiser
                echo $this->partial('magazine-article/bloc/_headlineArticleList.phtml', array('headlineRow' => $this->headlineRow, 'childRowset' => $this->childRowset, 'articleRow' => $this->articleRow, 'magazineRow' => $this->magazineRow));
            }
        ?>

        <?php if (null !== $this->appellationBlocRow) : ?>
        <h3 class="heading-6"><?php echo $this->translate('Appelation Associé') ?></h3>
        <div class="box-related-aoc">
            <div class="box-inner">
                <h3><?php echo $this->appellationBlocRow->name ?></h3>
                <a href="<?php echo $this->appellationBlocRow->permalink ?>" class="btn btn-push btn-lower">
                    <?php echo $this->translate('Voir la fiche AOC') ?>
                    <img src="/layouts/frontoffice/images/px.png" class="icon icon-arrow-next" height="16" width="16" />
                </a>
            </div>
        </div>

        <hr />
        <?php endif; ?>


        <?php if (!empty($this->evenementBlocRow)) : ?>
            <?php echo $this->partial('_partial/_evenement.phtml', array('evenementBlocRow' => $this->evenementBlocRow)) ?>
            <hr />
        <?php endif; ?>

        <?php if (null != $this->relatedArticleRowset) : ?>
        <h3 class="heading-6"><?php echo $this->translate('Actualités') ?></h3>
        <ul class="news-list">
            <?php foreach ($this->relatedArticleRowset as $relatedArticleRow) : ?>
            <li>
                <a href="<?php echo $relatedArticleRow->permalink; ?>">
                    <img src="<?php echo $relatedArticleRow->article->getCoverOrPx()->getStaticUrl(array('cropcenterresize' => array('width' => '60', 'height' => '60'))); ?>" height="60" width="60" class="picture media-illus" />
                    <div class="media-inner">
                        <strong><?php echo $relatedArticleRow->article->title; ?></strong>
                            <small><?php echo $relatedArticleRow->article->getDateObjectBy('published_at')->get('dd.MM.YYY'); ?></small>
                    </div>
                </a>
            </li>
            <?php endforeach; ?>
        </ul>

        <hr />
        <?php endif; ?>

        <?php if (null != $this->lastArticleRowset) : ?>
        <h3 class="heading-6"><?php echo $this->translate('Dernières actualités') ?></h3>
        <ul class="news-list">
            <?php foreach ($this->lastArticleRowset as $lastArticleRow) : ?>
            <li>
                <a href="<?php echo $lastArticleRow->permalink; ?>">
                    <img src="<?php echo $lastArticleRow->article->getCoverOrPx()->getStaticUrl(array('cropcenterresize' => array('width' => '60', 'height' => '60'))); ?>" height="60" width="60" class="picture media-illus" />
                    <div class="media-inner">
                        <strong><?php echo $lastArticleRow->article->title; ?></strong>
                            <small><?php echo $lastArticleRow->article->getDateObjectBy('published_at')->get('dd.MM.YYY'); ?></small>
                    </div>
                </a>
            </li>
            <?php endforeach; ?>
        </ul>

        <hr />
        <?php endif; ?>

    </section>
</div>
</div>



<?php $this->placeholder('sub-footer')->captureStart(); ?>

<!--<div class="row box-proposal">-->
<!--    <div class="cell-9">-->
<!--        --><?php //foreach ($this->profileRowser as $profileRow) : ?>
<!--            <img src="--><?php //$profileRow->getAvatarOrPx()->getStaticUrl(array('cropcenterresize' => array('width' => '95', 'height' => '83'))) ?><!--" height="83" width="95" class="picture float-left" />-->
<!--        --><?php //endforeach; ?>
<!--    </div>-->
<!--    <div class="cell-3 cell-last">-->
<!--        <h4>--><?php //echo $this->translate('Proposez <span>Votre article</span>') ?><!--</h4>-->
<!--        <a href="--><?php //echo $this->url(array(), 'ir_share_form') ?><!--" class="btn btn-push btn-lower">-->
<!--            --><?php //echo $this->translate('Envoyer un article') ?>
<!--            <img src="/layouts/frontoffice/images/px.png" class="icon icon-arrow-next" height="16" width="16" />-->
<!--        </a>-->
<!--    </div>-->
<!--</div>-->

<?php $this->placeholder('sub-footer')->captureEnd(); ?>


