<?php

$this->gridForm()->addHeader($this->form, array(
    'elements' => array('title')
));

$this->gridForm()->addMain($this->form, array(
    'label'    => $this->translate('Main'),
    'elements' => array('description', 'media')
));

$this->gridForm()->addMain($this->form, array(
    'label'    => $this->translate('SEO'),
    'elements' => array('slug')
));

$this->gridForm()->addMain($this->form, array(
    'label'       => $this->translate('Tags'),
    'elements' => array('newtags', 'tags')
));

$this->gridForm()->addAside($this->form, array(
    'label' => $this->translate('Publication infos'),
    'elements' => array('is_valid', 'is_contributed')
));

$this->gridForm()->addAside($this->form, array(
    'label' => $this->translate('Configuration'),
    'elements' => array('author_id', 'has_comment')
));

echo $this->partial('grid/_form.phtml', $this);