<?php

$this->gridForm()->addHeader($this->form, array(
    'elements' => array('name')
));

$this->gridForm()->addMain($this->form, array(
	'label'	   => $this->translate('SEO'),
    'elements' => array('slug')
));

$this->gridForm()->addMain($this->form, array(
    'label'	   => $this->translate('n:m'),
    'elements' => array('articles', 'evenements', 'medias')
));

echo $this->partial('grid/_form.phtml', $this);