<?php $this->placeholder('sub-header')->captureStart(); ?>
<div class="row">
    <div class="cell-10 append-1 prepend-1 cell-last">
        <h1 class="heading-10"><?php echo $this->magazineRow->title ?></h1>
    </div>
</div>
<?php $this->placeholder('sub-header')->captureEnd(); ?>

<php //@TODO: Dynamiser navigation magazine ?>
<?php $this->placeholder('sub-header-menu')->captureStart(); ?>
<div class="row">
    <div class="cell-12 cell-last">
        <nav class="inlinemenu-list">
            <ul>
                <li><a href="#">Agenda</a></li>
                <li class="active"><a href="#">Dossier du mois</a></li>
                <li><a href="#">Mediathèque</a></li>
            </ul>
        </nav>
    </div>
</div>
<?php $this->placeholder('sub-header-menu')->captureEnd(); ?>