<?php if ($this->pageCount): ?>
<div id="paginationControl">

<!-- Previous page link --> 
<?php if (isset($this->previous)): ?> 
  <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">&lt; <?php echo "précédent"; ?></a> | 
<?php else: ?> 
  <span class="disabled">&lt; <?php echo "précédent"; ?></span> | 
<?php endif; ?> 

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?> 
  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a> | 
  <?php else: ?>
    <span class="current"><?php echo $page; ?></span> | 
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link --> 
<?php if (isset($this->next)): ?> 
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>"><?php echo "suivant" ?> &gt;</a>
<?php else: ?> 
  <span class="disabled"><?php echo "suivant" ?> &gt;</span>
<?php endif; ?> 
</div> 
<?php endif; ?>