<?php $this->placeholder('sub-header')->captureStart(); ?>
<div class="row">
    <div class="cell-10 append-1 prepend-1 cell-last">
        <h1 class="heading-10"><?php echo $this->magazineRow->title ?></h1>
    </div>
</div>
<?php $this->placeholder('sub-header')->captureEnd(); ?>

<?php $this->placeholder('sub-header-menu')->captureStart(); ?>
<div class="row">
    <div class="cell-12 cell-last">
        <nav class="inlinemenu-list">
            <ul>
                <?php foreach ($this->navigation as $navigation) : ?>
                    <li <?php echo ($navigation['url'] == $this->url) ? 'class="active"' : ''; ?>><a href="<?php echo $navigation['url'] ?>"><?php echo $navigation['name'] ?></a></li>
                <?php endforeach; ?>
            </ul>
        </nav>
    </div>
</div>
<?php $this->placeholder('sub-header-menu')->captureEnd(); ?>