<?php

$this->gridForm()->addHeader($this->form, array(
    'elements' => array('name')
));

$this->gridForm()->addMain($this->form, array(
    'noFieldset' => true,
    'elements' => array('body')
));

$this->gridForm()->addMain($this->form, array(
	'label'	   => $this->translate('Properties'),
    'elements' => array('css_class', 'pagination_item', 'cover', 'icon', 'parent')
));

$this->gridForm()->addMain($this->form, array(
	'label'	   => $this->translate('n:m'),
    'elements' => array('articles')
));

$this->gridForm()->addMain($this->form, array(
	'label'	   => $this->translate('SEO'),
    'elements' => array('slug')
));

$this->gridForm()->addAside($this->form, array(
    'label' => $this->translate('Publication status'),
    'elements' => array('is_online')
));

echo $this->partial('grid/_form.phtml', $this);